
##Run dRep for all genomes generated by single sample assembly parts
drep_dir=$1
threads=$2

dRep dereplicate \
${drep_dir} \
-g ${drep_dir}/bins/*fa \
--genomeInfo ${drep_dir}/genomeInfo.csv \
-sa 0.95 \
-nc 0.30 \
-ms 10000 \
-strW 0 \
-centW 0 \
-p ${threads} \
-comp 50 \
-con 5